/* ═══════════════════════════════════════════════════════════════
 *  guide-data.js — 가이드 글 조회수 데이터 (운영자 편집 파일)
 *  ───────────────────────────────────────────────────────────────
 *  ▶ GA에서 조회수 확인 후 이 숫자만 수정하세요. (코드 수정 불필요)
 *     GA4 > 보고서 > 참여도 > 페이지 및 화면 → 각 글의 조회수를 확인해
 *     아래 해당 글의 숫자를 바꾸면, 사이트가 이 값 기준으로 인기순 자동 정렬합니다.
 *  ▶ 숫자가 클수록 카테고리 상단·인기 가이드 TOP5 위로 올라갑니다.
 *  ▶ 값이 같거나 없으면 최신 작성일 순으로 보조 정렬됩니다.
 *  ▶ 아래 값은 임시 예시입니다. 실제 GA 조회수로 교체하세요.
 * ═══════════════════════════════════════════════════════════════ */
window.SOHO_GUIDE_VIEWS = {
  "self-employed-injury-insurance.html": 1500,
  "store-electricity-bill-reduce.html": 1490,
  "store-transfer-tax.html": 1480,
  "bad-review-legal-response.html": 1470,
  "store-theft-insurance-claim.html": 1460,
  "loyalty-point-system.html": 1450,
  "card-sales-tax-audit.html": 1440,
  "employee-termination-guide.html": 1430,
  "parttime-hiring-solution.html": 1420,
  "premium-money-dispute.html": 1410,
  "instagram-algorithm-2026.html": 1400,
  "delivery-only-marketing.html": 1390,
  "soho-delivery-cost-breakdown.html": 1380,
  "academy-fitness-marketing.html": 1370,
  "unpaid-settlement-dispute.html": 1360,
  "soho-delivery-cost-reduction.html": 1350,
  "employee-insurance-cost.html": 1340,
  "retail-store-marketing.html": 1330,
  "store-cleaning-checklist.html": 1320,
  "beauty-salon-marketing.html": 1310,
  "management-voucher-2026.html": 1300,
  "store-lease-agreement-checklist.html": 1290,
  "cafe-marketing-by-type.html": 1280,
  "naver-place-ranking-2026.html": 1270,
  "soho-loan-refinancing.html": 1260,
  "solo-shop-tax-deduction.html": 1250,
  "store-cctv-guide.html": 1240,
  "soho-digital-marketing-agency-selection.html": 1230,
  "baemin-takeout-vs-delivery.html": 1220,
  "store-signage-design.html": 1210,
  "soho-cash-receipt-guide.html": 1200,
  "rent-increase-refusal.html": 1190,
  "soho-bookkeeping-app.html": 1180,
  "store-staff-management-2026.html": 1170,
  "phone-marketing-script.html": 1160,
  "public-vs-private-delivery.html": 1150,
  "store-cleaning-business-tips.html": 1140,
  "cold-noodle-summer-menu.html": 1130,
  "soho-delivery-cost-analysis.html": 1120,
  "store-fire-safety-tips.html": 1110,
  "store-contract-termination.html": 1100,
  "store-lease-renewal-rights.html": 1090,
  "google-business-profile.html": 1080,
  "heatwave-sales-strategy.html": 1070,
  "soho-health-checkup.html": 1060,
  "online-order-system.html": 1050,
  "instagram-ads-budget.html": 1040,
  "business-license-types.html": 1030,
  "pos-system-guide.html": 1020,
  "baemin-ultraol-vs-openlist.html": 1010,
  "card-terminal-compare.html": 1000,
  "naver-place-photo-upload.html": 990,
  "restaurant-business-registration.html": 980,
  "durunuri-application.html": 970,
  "noran-umbrella-cancel.html": 960,
  "tax-refund-soho.html": 950,
  "coupangeats-review.html": 940,
  "policy-loan-guide.html": 930,
  "restaurant-startup-cost.html": 920,
  "summer-restaurant-marketing.html": 910,
  "baemin-vs-coupang.html": 900,
  "food-poisoning-prevention.html": 890,
  "general-vs-simple-tax.html": 880,
  "soho-2026-second-half-support.html": 870,
  "cafe-startup-real-cost.html": 860,
  "instagram-follower-zero.html": 850,
  "soho-jiwongeum-2026.html": 840,
  "youtube-shorts-marketing.html": 830,
  "delivery-ad-reduce.html": 820,
  "naver-place-review.html": 810,
  "instagram-restaurant.html": 800,
  "naver-blog-seo.html": 790,
  "daangn-marketing.html": 780,
  "menu-design-tips.html": 770,
  "noran-umbrella.html": 760,
  "delivery-photo-tips.html": 750,
  "hygiene-grade.html": 740,
  "cheap-interior.html": 730,
  "kiosk-guide.html": 720,
  "closure-support.html": 710,
  "smart-store-guide.html": 700,
  "delivery-packaging.html": 690,
  "no-parking-marketing.html": 680,
  "fire-insurance.html": 670,
  "soho-sns-strategy.html": 660,
  "review-event.html": 650,
  "lunch-special-marketing.html": 640,
  "kakao-channel-marketing.html": 630,
  "naver-advertising.html": 620,
  "soho-accounting.html": 610,
  "peak-time-marketing.html": 600,
  "soho-minimum-wage.html": 590,
  "food-cost-control.html": 580,
  "weekend-event.html": 570
};
